/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IHederaTokenServiceLite, IHederaTokenServiceLiteInterface } from "../../../interfaces/IHederaTokenServiceLite.sol/IHederaTokenServiceLite.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "approved",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "serialNumber",
        "type": "uint256"
      }
    ],
    "name": "approveNFT",
    "outputs": [
      {
        "internalType": "int64",
        "name": "responseCode",
        "type": "int64"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      }
    ],
    "name": "associateToken",
    "outputs": [
      {
        "internalType": "int32",
        "name": "responseCode",
        "type": "int32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "address[]",
        "name": "tokens",
        "type": "address[]"
      }
    ],
    "name": "associateTokens",
    "outputs": [
      {
        "internalType": "int64",
        "name": "responseCode",
        "type": "int64"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "internalType": "string",
            "name": "name",
            "type": "string"
          },
          {
            "internalType": "string",
            "name": "symbol",
            "type": "string"
          },
          {
            "internalType": "address",
            "name": "treasury",
            "type": "address"
          },
          {
            "internalType": "string",
            "name": "memo",
            "type": "string"
          },
          {
            "internalType": "bool",
            "name": "tokenSupplyType",
            "type": "bool"
          },
          {
            "internalType": "int64",
            "name": "maxSupply",
            "type": "int64"
          },
          {
            "internalType": "bool",
            "name": "freezeDefault",
            "type": "bool"
          },
          {
            "components": [
              {
                "internalType": "uint256",
                "name": "keyType",
                "type": "uint256"
              },
              {
                "components": [
                  {
                    "internalType": "bool",
                    "name": "inheritAccountKey",
                    "type": "bool"
                  },
                  {
                    "internalType": "address",
                    "name": "contractId",
                    "type": "address"
                  },
                  {
                    "internalType": "bytes",
                    "name": "ed25519",
                    "type": "bytes"
                  },
                  {
                    "internalType": "bytes",
                    "name": "ECDSA_secp256k1",
                    "type": "bytes"
                  },
                  {
                    "internalType": "address",
                    "name": "delegatableContractId",
                    "type": "address"
                  }
                ],
                "internalType": "struct IHederaTokenServiceLite.KeyValue",
                "name": "keyValue",
                "type": "tuple"
              }
            ],
            "internalType": "struct IHederaTokenServiceLite.TokenKey[]",
            "name": "tokenKeys",
            "type": "tuple[]"
          },
          {
            "components": [
              {
                "internalType": "uint32",
                "name": "second",
                "type": "uint32"
              },
              {
                "internalType": "address",
                "name": "autoRenewAccount",
                "type": "address"
              },
              {
                "internalType": "uint32",
                "name": "autoRenewPeriod",
                "type": "uint32"
              }
            ],
            "internalType": "struct IHederaTokenServiceLite.Expiry",
            "name": "expiry",
            "type": "tuple"
          }
        ],
        "internalType": "struct IHederaTokenServiceLite.HederaToken",
        "name": "token",
        "type": "tuple"
      },
      {
        "components": [
          {
            "internalType": "uint32",
            "name": "amount",
            "type": "uint32"
          },
          {
            "internalType": "address",
            "name": "tokenId",
            "type": "address"
          },
          {
            "internalType": "bool",
            "name": "useHbarsForPayment",
            "type": "bool"
          },
          {
            "internalType": "bool",
            "name": "useCurrentTokenForPayment",
            "type": "bool"
          },
          {
            "internalType": "address",
            "name": "feeCollector",
            "type": "address"
          }
        ],
        "internalType": "struct IHederaTokenServiceLite.FixedFee[]",
        "name": "fixedFees",
        "type": "tuple[]"
      },
      {
        "components": [
          {
            "internalType": "uint32",
            "name": "numerator",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "denominator",
            "type": "uint32"
          },
          {
            "internalType": "uint32",
            "name": "amount",
            "type": "uint32"
          },
          {
            "internalType": "address",
            "name": "tokenId",
            "type": "address"
          },
          {
            "internalType": "bool",
            "name": "useHbarsForPayment",
            "type": "bool"
          },
          {
            "internalType": "address",
            "name": "feeCollector",
            "type": "address"
          }
        ],
        "internalType": "struct IHederaTokenServiceLite.RoyaltyFee[]",
        "name": "royaltyFees",
        "type": "tuple[]"
      }
    ],
    "name": "createNonFungibleTokenWithCustomFees",
    "outputs": [
      {
        "internalType": "int32",
        "name": "responseCode",
        "type": "int32"
      },
      {
        "internalType": "address",
        "name": "tokenAddress",
        "type": "address"
      }
    ],
    "stateMutability": "payable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "components": [
          {
            "components": [
              {
                "internalType": "address",
                "name": "accountID",
                "type": "address"
              },
              {
                "internalType": "int64",
                "name": "amount",
                "type": "int64"
              },
              {
                "internalType": "bool",
                "name": "isApproval",
                "type": "bool"
              }
            ],
            "internalType": "struct IHederaTokenServiceLite.AccountAmount[]",
            "name": "transfers",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct IHederaTokenServiceLite.TransferList",
        "name": "transferList",
        "type": "tuple"
      },
      {
        "components": [
          {
            "internalType": "address",
            "name": "token",
            "type": "address"
          },
          {
            "components": [
              {
                "internalType": "address",
                "name": "accountID",
                "type": "address"
              },
              {
                "internalType": "int64",
                "name": "amount",
                "type": "int64"
              },
              {
                "internalType": "bool",
                "name": "isApproval",
                "type": "bool"
              }
            ],
            "internalType": "struct IHederaTokenServiceLite.AccountAmount[]",
            "name": "transfers",
            "type": "tuple[]"
          },
          {
            "components": [
              {
                "internalType": "address",
                "name": "senderAccountID",
                "type": "address"
              },
              {
                "internalType": "address",
                "name": "receiverAccountID",
                "type": "address"
              },
              {
                "internalType": "int64",
                "name": "serialNumber",
                "type": "int64"
              },
              {
                "internalType": "bool",
                "name": "isApproval",
                "type": "bool"
              }
            ],
            "internalType": "struct IHederaTokenServiceLite.NftTransfer[]",
            "name": "nftTransfers",
            "type": "tuple[]"
          }
        ],
        "internalType": "struct IHederaTokenServiceLite.TokenTransferList[]",
        "name": "tokenTransfers",
        "type": "tuple[]"
      }
    ],
    "name": "cryptoTransfer",
    "outputs": [
      {
        "internalType": "int64",
        "name": "responseCode",
        "type": "int64"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "uint64",
        "name": "amount",
        "type": "uint64"
      },
      {
        "internalType": "bytes[]",
        "name": "metadata",
        "type": "bytes[]"
      }
    ],
    "name": "mintToken",
    "outputs": [
      {
        "internalType": "int32",
        "name": "responseCode",
        "type": "int32"
      },
      {
        "internalType": "uint64",
        "name": "newTotalSupply",
        "type": "uint64"
      },
      {
        "internalType": "int64[]",
        "name": "serialNumbers",
        "type": "int64[]"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "operator",
        "type": "address"
      },
      {
        "internalType": "bool",
        "name": "approved",
        "type": "bool"
      }
    ],
    "name": "setApprovalForAll",
    "outputs": [
      {
        "internalType": "int64",
        "name": "responseCode",
        "type": "int64"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "sender",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "receiver",
        "type": "address"
      },
      {
        "internalType": "int64",
        "name": "serialNumber",
        "type": "int64"
      }
    ],
    "name": "transferNFT",
    "outputs": [
      {
        "internalType": "int32",
        "name": "responseCode",
        "type": "int32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "address[]",
        "name": "sender",
        "type": "address[]"
      },
      {
        "internalType": "address[]",
        "name": "receiver",
        "type": "address[]"
      },
      {
        "internalType": "int64[]",
        "name": "serialNumber",
        "type": "int64[]"
      }
    ],
    "name": "transferNFTs",
    "outputs": [
      {
        "internalType": "int32",
        "name": "responseCode",
        "type": "int32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "account",
        "type": "address"
      },
      {
        "internalType": "int64[]",
        "name": "serialNumbers",
        "type": "int64[]"
      }
    ],
    "name": "wipeTokenAccountNFT",
    "outputs": [
      {
        "internalType": "int32",
        "name": "responseCode",
        "type": "int32"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IHederaTokenServiceLite__factory {
    static readonly abi = _abi;
    static createInterface(): IHederaTokenServiceLiteInterface {
      return new Interface(_abi) as IHederaTokenServiceLiteInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IHederaTokenServiceLite {
      return new Contract(address, _abi, runner) as unknown as IHederaTokenServiceLite;
    }
  }
  