/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'FallbackTokenSwap', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.FallbackTokenSwap__factory>
getContractFactory(name: 'HederaTokenService', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.HederaTokenService__factory>
getContractFactory(name: 'IBurnableHTS', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IBurnableHTS__factory>
getContractFactory(name: 'IHederaTokenService', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IHederaTokenService__factory>
getContractFactory(name: 'IHederaTokenServiceLite', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IHederaTokenServiceLite__factory>
getContractFactory(name: 'ILazyDelegateRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ILazyDelegateRegistry__factory>
getContractFactory(name: 'ILazyGasStation', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ILazyGasStation__factory>
getContractFactory(name: 'IRoles', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IRoles__factory>
getContractFactory(name: 'LazyGasStation', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LazyGasStation__factory>
getContractFactory(name: 'KeyHelper', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.KeyHelper__factory>
getContractFactory(name: 'LAZYTokenCreator', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.LAZYTokenCreator__factory>
getContractFactory(name: 'NoFallbackTokenSwap', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.NoFallbackTokenSwap__factory>
getContractFactory(name: 'UnifiedTokenSwap', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.UnifiedTokenSwap__factory>

  getContractAt(name: 'FallbackTokenSwap', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.FallbackTokenSwap>
getContractAt(name: 'HederaTokenService', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.HederaTokenService>
getContractAt(name: 'IBurnableHTS', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IBurnableHTS>
getContractAt(name: 'IHederaTokenService', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IHederaTokenService>
getContractAt(name: 'IHederaTokenServiceLite', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IHederaTokenServiceLite>
getContractAt(name: 'ILazyDelegateRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ILazyDelegateRegistry>
getContractAt(name: 'ILazyGasStation', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ILazyGasStation>
getContractAt(name: 'IRoles', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IRoles>
getContractAt(name: 'LazyGasStation', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LazyGasStation>
getContractAt(name: 'KeyHelper', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.KeyHelper>
getContractAt(name: 'LAZYTokenCreator', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.LAZYTokenCreator>
getContractAt(name: 'NoFallbackTokenSwap', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.NoFallbackTokenSwap>
getContractAt(name: 'UnifiedTokenSwap', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.UnifiedTokenSwap>

  deployContract(name: 'FallbackTokenSwap', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FallbackTokenSwap>
deployContract(name: 'HederaTokenService', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HederaTokenService>
deployContract(name: 'IBurnableHTS', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBurnableHTS>
deployContract(name: 'IHederaTokenService', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IHederaTokenService>
deployContract(name: 'IHederaTokenServiceLite', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IHederaTokenServiceLite>
deployContract(name: 'ILazyDelegateRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILazyDelegateRegistry>
deployContract(name: 'ILazyGasStation', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILazyGasStation>
deployContract(name: 'IRoles', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRoles>
deployContract(name: 'LazyGasStation', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LazyGasStation>
deployContract(name: 'KeyHelper', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KeyHelper>
deployContract(name: 'LAZYTokenCreator', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LAZYTokenCreator>
deployContract(name: 'NoFallbackTokenSwap', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoFallbackTokenSwap>
deployContract(name: 'UnifiedTokenSwap', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UnifiedTokenSwap>

  deployContract(name: 'FallbackTokenSwap', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.FallbackTokenSwap>
deployContract(name: 'HederaTokenService', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.HederaTokenService>
deployContract(name: 'IBurnableHTS', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IBurnableHTS>
deployContract(name: 'IHederaTokenService', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IHederaTokenService>
deployContract(name: 'IHederaTokenServiceLite', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IHederaTokenServiceLite>
deployContract(name: 'ILazyDelegateRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILazyDelegateRegistry>
deployContract(name: 'ILazyGasStation', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ILazyGasStation>
deployContract(name: 'IRoles', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IRoles>
deployContract(name: 'LazyGasStation', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LazyGasStation>
deployContract(name: 'KeyHelper', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.KeyHelper>
deployContract(name: 'LAZYTokenCreator', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.LAZYTokenCreator>
deployContract(name: 'NoFallbackTokenSwap', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.NoFallbackTokenSwap>
deployContract(name: 'UnifiedTokenSwap', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UnifiedTokenSwap>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  