/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IBurnableHTS, IBurnableHTSInterface } from "../../../interfaces/IBurnableHTS.sol/IBurnableHTS.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "token",
        "type": "address"
      },
      {
        "internalType": "uint32",
        "name": "amount",
        "type": "uint32"
      }
    ],
    "name": "burn",
    "outputs": [
      {
        "internalType": "int256",
        "name": "responseCode",
        "type": "int256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IBurnableHTS__factory {
    static readonly abi = _abi;
    static createInterface(): IBurnableHTSInterface {
      return new Interface(_abi) as IBurnableHTSInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IBurnableHTS {
      return new Contract(address, _abi, runner) as unknown as IBurnableHTS;
    }
  }
  