/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace IHederaTokenServiceLite {
      
    export type KeyValueStruct = {inheritAccountKey: boolean, contractId: AddressLike, ed25519: BytesLike, ECDSA_secp256k1: BytesLike, delegatableContractId: AddressLike}

    export type KeyValueStructOutput = [inheritAccountKey: boolean, contractId: string, ed25519: string, ECDSA_secp256k1: string, delegatableContractId: string] & {inheritAccountKey: boolean, contractId: string, ed25519: string, ECDSA_secp256k1: string, delegatableContractId: string }
  

    export type TokenKeyStruct = {keyType: BigNumberish, keyValue: IHederaTokenServiceLite.KeyValueStruct}

    export type TokenKeyStructOutput = [keyType: bigint, keyValue: IHederaTokenServiceLite.KeyValueStructOutput] & {keyType: bigint, keyValue: IHederaTokenServiceLite.KeyValueStructOutput }
  

    export type ExpiryStruct = {second: BigNumberish, autoRenewAccount: AddressLike, autoRenewPeriod: BigNumberish}

    export type ExpiryStructOutput = [second: bigint, autoRenewAccount: string, autoRenewPeriod: bigint] & {second: bigint, autoRenewAccount: string, autoRenewPeriod: bigint }
  

    export type HederaTokenStruct = {name: string, symbol: string, treasury: AddressLike, memo: string, tokenSupplyType: boolean, maxSupply: BigNumberish, freezeDefault: boolean, tokenKeys: IHederaTokenServiceLite.TokenKeyStruct[], expiry: IHederaTokenServiceLite.ExpiryStruct}

    export type HederaTokenStructOutput = [name: string, symbol: string, treasury: string, memo: string, tokenSupplyType: boolean, maxSupply: bigint, freezeDefault: boolean, tokenKeys: IHederaTokenServiceLite.TokenKeyStructOutput[], expiry: IHederaTokenServiceLite.ExpiryStructOutput] & {name: string, symbol: string, treasury: string, memo: string, tokenSupplyType: boolean, maxSupply: bigint, freezeDefault: boolean, tokenKeys: IHederaTokenServiceLite.TokenKeyStructOutput[], expiry: IHederaTokenServiceLite.ExpiryStructOutput }
  

    export type FixedFeeStruct = {amount: BigNumberish, tokenId: AddressLike, useHbarsForPayment: boolean, useCurrentTokenForPayment: boolean, feeCollector: AddressLike}

    export type FixedFeeStructOutput = [amount: bigint, tokenId: string, useHbarsForPayment: boolean, useCurrentTokenForPayment: boolean, feeCollector: string] & {amount: bigint, tokenId: string, useHbarsForPayment: boolean, useCurrentTokenForPayment: boolean, feeCollector: string }
  

    export type RoyaltyFeeStruct = {numerator: BigNumberish, denominator: BigNumberish, amount: BigNumberish, tokenId: AddressLike, useHbarsForPayment: boolean, feeCollector: AddressLike}

    export type RoyaltyFeeStructOutput = [numerator: bigint, denominator: bigint, amount: bigint, tokenId: string, useHbarsForPayment: boolean, feeCollector: string] & {numerator: bigint, denominator: bigint, amount: bigint, tokenId: string, useHbarsForPayment: boolean, feeCollector: string }
  

    export type AccountAmountStruct = {accountID: AddressLike, amount: BigNumberish, isApproval: boolean}

    export type AccountAmountStructOutput = [accountID: string, amount: bigint, isApproval: boolean] & {accountID: string, amount: bigint, isApproval: boolean }
  

    export type TransferListStruct = {transfers: IHederaTokenServiceLite.AccountAmountStruct[]}

    export type TransferListStructOutput = [transfers: IHederaTokenServiceLite.AccountAmountStructOutput[]] & {transfers: IHederaTokenServiceLite.AccountAmountStructOutput[] }
  

    export type NftTransferStruct = {senderAccountID: AddressLike, receiverAccountID: AddressLike, serialNumber: BigNumberish, isApproval: boolean}

    export type NftTransferStructOutput = [senderAccountID: string, receiverAccountID: string, serialNumber: bigint, isApproval: boolean] & {senderAccountID: string, receiverAccountID: string, serialNumber: bigint, isApproval: boolean }
  

    export type TokenTransferListStruct = {token: AddressLike, transfers: IHederaTokenServiceLite.AccountAmountStruct[], nftTransfers: IHederaTokenServiceLite.NftTransferStruct[]}

    export type TokenTransferListStructOutput = [token: string, transfers: IHederaTokenServiceLite.AccountAmountStructOutput[], nftTransfers: IHederaTokenServiceLite.NftTransferStructOutput[]] & {token: string, transfers: IHederaTokenServiceLite.AccountAmountStructOutput[], nftTransfers: IHederaTokenServiceLite.NftTransferStructOutput[] }
  
    }

  export interface IHederaTokenServiceLiteInterface extends Interface {
    getFunction(nameOrSignature: "approveNFT" | "associateToken" | "associateTokens" | "createNonFungibleTokenWithCustomFees" | "cryptoTransfer" | "mintToken" | "setApprovalForAll" | "transferNFT" | "transferNFTs" | "wipeTokenAccountNFT"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'approveNFT', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'associateToken', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'associateTokens', values: [AddressLike, AddressLike[]]): string;
encodeFunctionData(functionFragment: 'createNonFungibleTokenWithCustomFees', values: [IHederaTokenServiceLite.HederaTokenStruct, IHederaTokenServiceLite.FixedFeeStruct[], IHederaTokenServiceLite.RoyaltyFeeStruct[]]): string;
encodeFunctionData(functionFragment: 'cryptoTransfer', values: [IHederaTokenServiceLite.TransferListStruct, IHederaTokenServiceLite.TokenTransferListStruct[]]): string;
encodeFunctionData(functionFragment: 'mintToken', values: [AddressLike, BigNumberish, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'setApprovalForAll', values: [AddressLike, AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'transferNFT', values: [AddressLike, AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferNFTs', values: [AddressLike, AddressLike[], AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'wipeTokenAccountNFT', values: [AddressLike, AddressLike, BigNumberish[]]): string;

    decodeFunctionResult(functionFragment: 'approveNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'associateToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'associateTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createNonFungibleTokenWithCustomFees', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cryptoTransfer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'mintToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setApprovalForAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferNFTs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'wipeTokenAccountNFT', data: BytesLike): Result;
  }

  

  export interface IHederaTokenServiceLite extends BaseContract {
    
    connect(runner?: ContractRunner | null): IHederaTokenServiceLite;
    waitForDeployment(): Promise<this>;

    interface: IHederaTokenServiceLiteInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    approveNFT: TypedContractMethod<
      [token: AddressLike, approved: AddressLike, serialNumber: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    associateToken: TypedContractMethod<
      [account: AddressLike, token: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    associateTokens: TypedContractMethod<
      [account: AddressLike, tokens: AddressLike[], ],
      [bigint],
      'nonpayable'
    >
    

    
    createNonFungibleTokenWithCustomFees: TypedContractMethod<
      [token: IHederaTokenServiceLite.HederaTokenStruct, fixedFees: IHederaTokenServiceLite.FixedFeeStruct[], royaltyFees: IHederaTokenServiceLite.RoyaltyFeeStruct[], ],
      [[bigint, string] & {responseCode: bigint, tokenAddress: string }],
      'payable'
    >
    

    
    cryptoTransfer: TypedContractMethod<
      [transferList: IHederaTokenServiceLite.TransferListStruct, tokenTransfers: IHederaTokenServiceLite.TokenTransferListStruct[], ],
      [bigint],
      'nonpayable'
    >
    

    
    mintToken: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, metadata: BytesLike[], ],
      [[bigint, bigint, bigint[]] & {responseCode: bigint, newTotalSupply: bigint, serialNumbers: bigint[] }],
      'nonpayable'
    >
    

    
    setApprovalForAll: TypedContractMethod<
      [token: AddressLike, operator: AddressLike, approved: boolean, ],
      [bigint],
      'nonpayable'
    >
    

    
    transferNFT: TypedContractMethod<
      [token: AddressLike, sender: AddressLike, receiver: AddressLike, serialNumber: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    transferNFTs: TypedContractMethod<
      [token: AddressLike, sender: AddressLike[], receiver: AddressLike[], serialNumber: BigNumberish[], ],
      [bigint],
      'nonpayable'
    >
    

    
    wipeTokenAccountNFT: TypedContractMethod<
      [token: AddressLike, account: AddressLike, serialNumbers: BigNumberish[], ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'approveNFT'): TypedContractMethod<
      [token: AddressLike, approved: AddressLike, serialNumber: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'associateToken'): TypedContractMethod<
      [account: AddressLike, token: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'associateTokens'): TypedContractMethod<
      [account: AddressLike, tokens: AddressLike[], ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createNonFungibleTokenWithCustomFees'): TypedContractMethod<
      [token: IHederaTokenServiceLite.HederaTokenStruct, fixedFees: IHederaTokenServiceLite.FixedFeeStruct[], royaltyFees: IHederaTokenServiceLite.RoyaltyFeeStruct[], ],
      [[bigint, string] & {responseCode: bigint, tokenAddress: string }],
      'payable'
    >;
getFunction(nameOrSignature: 'cryptoTransfer'): TypedContractMethod<
      [transferList: IHederaTokenServiceLite.TransferListStruct, tokenTransfers: IHederaTokenServiceLite.TokenTransferListStruct[], ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'mintToken'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, metadata: BytesLike[], ],
      [[bigint, bigint, bigint[]] & {responseCode: bigint, newTotalSupply: bigint, serialNumbers: bigint[] }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setApprovalForAll'): TypedContractMethod<
      [token: AddressLike, operator: AddressLike, approved: boolean, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferNFT'): TypedContractMethod<
      [token: AddressLike, sender: AddressLike, receiver: AddressLike, serialNumber: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferNFTs'): TypedContractMethod<
      [token: AddressLike, sender: AddressLike[], receiver: AddressLike[], serialNumber: BigNumberish[], ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'wipeTokenAccountNFT'): TypedContractMethod<
      [token: AddressLike, account: AddressLike, serialNumbers: BigNumberish[], ],
      [bigint],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }