/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as keyHelperSol from './KeyHelper.sol/index.js';
export type { keyHelperSol };
import type * as lazyTokenCreatorSol from './LAZYTokenCreator.sol/index.js';
export type { lazyTokenCreatorSol };