/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface ILazyDelegateRegistryInterface extends Interface {
    getFunction(nameOrSignature: "checkDelegateToken" | "checkDelegateWallet" | "delegateNFT" | "delegateNFTs" | "delegateWalletTo" | "getDelegateWallet" | "getDelegatedNFTsBy" | "getNFTDelegatedTo" | "getNFTListDelegatedTo" | "getNFTsDelegatedTo" | "getSerialsDelegatedBy" | "getSerialsDelegatedByRange" | "getSerialsDelegatedTo" | "getTokensWithDelegates" | "getTokensWithDelegatesRange" | "getTotalTokensWithDelegates" | "getTotalWalletsWithDelegates" | "getWalletsDelegatedTo" | "getWalletsWithDelegates" | "getWalletsWithDelegatesRange" | "revokeDelegateNFT" | "revokeDelegateNFTs" | "revokeDelegateWallet"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "TokenDelegated" | "WalletDelegated"): EventFragment;

    encodeFunctionData(functionFragment: 'checkDelegateToken', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'checkDelegateWallet', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'delegateNFT', values: [AddressLike, AddressLike, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'delegateNFTs', values: [AddressLike, AddressLike[], BigNumberish[][]]): string;
encodeFunctionData(functionFragment: 'delegateWalletTo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getDelegateWallet', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getDelegatedNFTsBy', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'getNFTDelegatedTo', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getNFTListDelegatedTo', values: [AddressLike[], BigNumberish[][]]): string;
encodeFunctionData(functionFragment: 'getNFTsDelegatedTo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getSerialsDelegatedBy', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getSerialsDelegatedByRange', values: [AddressLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getSerialsDelegatedTo', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'getTokensWithDelegates', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTokensWithDelegatesRange', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTotalTokensWithDelegates', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTotalWalletsWithDelegates', values?: undefined): string;
encodeFunctionData(functionFragment: 'getWalletsDelegatedTo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getWalletsWithDelegates', values?: undefined): string;
encodeFunctionData(functionFragment: 'getWalletsWithDelegatesRange', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeDelegateNFT', values: [AddressLike, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'revokeDelegateNFTs', values: [AddressLike[], BigNumberish[][]]): string;
encodeFunctionData(functionFragment: 'revokeDelegateWallet', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'checkDelegateToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkDelegateWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'delegateNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'delegateNFTs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'delegateWalletTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDelegateWallet', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getDelegatedNFTsBy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getNFTDelegatedTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getNFTListDelegatedTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getNFTsDelegatedTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSerialsDelegatedBy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSerialsDelegatedByRange', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSerialsDelegatedTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokensWithDelegates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokensWithDelegatesRange', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalTokensWithDelegates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTotalWalletsWithDelegates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWalletsDelegatedTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWalletsWithDelegates', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getWalletsWithDelegatesRange', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeDelegateNFT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeDelegateNFTs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeDelegateWallet', data: BytesLike): Result;
  }

  
    export namespace TokenDelegatedEvent {
      export type InputTuple = [_token: AddressLike, _serial: BigNumberish, _delegate: AddressLike, _owner: AddressLike, _delegated: boolean];
      export type OutputTuple = [_token: string, _serial: bigint, _delegate: string, _owner: string, _delegated: boolean];
      export interface OutputObject {_token: string, _serial: bigint, _delegate: string, _owner: string, _delegated: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WalletDelegatedEvent {
      export type InputTuple = [_wallet: AddressLike, _delegate: AddressLike, _delegated: boolean];
      export type OutputTuple = [_wallet: string, _delegate: string, _delegated: boolean];
      export interface OutputObject {_wallet: string, _delegate: string, _delegated: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ILazyDelegateRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): ILazyDelegateRegistry;
    waitForDeployment(): Promise<this>;

    interface: ILazyDelegateRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    checkDelegateToken: TypedContractMethod<
      [_proposedDelegate: AddressLike, _token: AddressLike, _serial: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    checkDelegateWallet: TypedContractMethod<
      [_actualWallet: AddressLike, _proposedDelegate: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    delegateNFT: TypedContractMethod<
      [_delegate: AddressLike, _token: AddressLike, _serials: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    delegateNFTs: TypedContractMethod<
      [_delegate: AddressLike, _tokens: AddressLike[], _serials: BigNumberish[][], ],
      [void],
      'nonpayable'
    >
    

    
    delegateWalletTo: TypedContractMethod<
      [_delegate: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    getDelegateWallet: TypedContractMethod<
      [_wallet: AddressLike, ],
      [string],
      'view'
    >
    

    
    getDelegatedNFTsBy: TypedContractMethod<
      [_ownerWallet: AddressLike, _includeSerials: boolean, ],
      [[string[], bigint[][]] & {tokens: string[], serials: bigint[][] }],
      'view'
    >
    

    
    getNFTDelegatedTo: TypedContractMethod<
      [_token: AddressLike, _serial: BigNumberish, ],
      [string],
      'view'
    >
    

    
    getNFTListDelegatedTo: TypedContractMethod<
      [_tokens: AddressLike[], _serials: BigNumberish[][], ],
      [string[][]],
      'view'
    >
    

    
    getNFTsDelegatedTo: TypedContractMethod<
      [_delegate: AddressLike, ],
      [[string[], bigint[][]] & {tokens: string[], serials: bigint[][] }],
      'view'
    >
    

    
    getSerialsDelegatedBy: TypedContractMethod<
      [_ownerWallet: AddressLike, _token: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getSerialsDelegatedByRange: TypedContractMethod<
      [_ownerWallet: AddressLike, _token: AddressLike, _from: BigNumberish, _to: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    getSerialsDelegatedTo: TypedContractMethod<
      [_delegate: AddressLike, _token: AddressLike, ],
      [bigint[]],
      'view'
    >
    

    
    getTokensWithDelegates: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getTokensWithDelegatesRange: TypedContractMethod<
      [_from: BigNumberish, _to: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    getTotalTokensWithDelegates: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getTotalWalletsWithDelegates: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getWalletsDelegatedTo: TypedContractMethod<
      [_delegateWallet: AddressLike, ],
      [string[]],
      'view'
    >
    

    
    getWalletsWithDelegates: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getWalletsWithDelegatesRange: TypedContractMethod<
      [_from: BigNumberish, _to: BigNumberish, ],
      [string[]],
      'view'
    >
    

    
    revokeDelegateNFT: TypedContractMethod<
      [_token: AddressLike, _serial: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    revokeDelegateNFTs: TypedContractMethod<
      [_tokens: AddressLike[], _serials: BigNumberish[][], ],
      [void],
      'nonpayable'
    >
    

    
    revokeDelegateWallet: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'checkDelegateToken'): TypedContractMethod<
      [_proposedDelegate: AddressLike, _token: AddressLike, _serial: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'checkDelegateWallet'): TypedContractMethod<
      [_actualWallet: AddressLike, _proposedDelegate: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'delegateNFT'): TypedContractMethod<
      [_delegate: AddressLike, _token: AddressLike, _serials: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'delegateNFTs'): TypedContractMethod<
      [_delegate: AddressLike, _tokens: AddressLike[], _serials: BigNumberish[][], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'delegateWalletTo'): TypedContractMethod<
      [_delegate: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getDelegateWallet'): TypedContractMethod<
      [_wallet: AddressLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getDelegatedNFTsBy'): TypedContractMethod<
      [_ownerWallet: AddressLike, _includeSerials: boolean, ],
      [[string[], bigint[][]] & {tokens: string[], serials: bigint[][] }],
      'view'
    >;
getFunction(nameOrSignature: 'getNFTDelegatedTo'): TypedContractMethod<
      [_token: AddressLike, _serial: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getNFTListDelegatedTo'): TypedContractMethod<
      [_tokens: AddressLike[], _serials: BigNumberish[][], ],
      [string[][]],
      'view'
    >;
getFunction(nameOrSignature: 'getNFTsDelegatedTo'): TypedContractMethod<
      [_delegate: AddressLike, ],
      [[string[], bigint[][]] & {tokens: string[], serials: bigint[][] }],
      'view'
    >;
getFunction(nameOrSignature: 'getSerialsDelegatedBy'): TypedContractMethod<
      [_ownerWallet: AddressLike, _token: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getSerialsDelegatedByRange'): TypedContractMethod<
      [_ownerWallet: AddressLike, _token: AddressLike, _from: BigNumberish, _to: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getSerialsDelegatedTo'): TypedContractMethod<
      [_delegate: AddressLike, _token: AddressLike, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTokensWithDelegates'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTokensWithDelegatesRange'): TypedContractMethod<
      [_from: BigNumberish, _to: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalTokensWithDelegates'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getTotalWalletsWithDelegates'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getWalletsDelegatedTo'): TypedContractMethod<
      [_delegateWallet: AddressLike, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getWalletsWithDelegates'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getWalletsWithDelegatesRange'): TypedContractMethod<
      [_from: BigNumberish, _to: BigNumberish, ],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'revokeDelegateNFT'): TypedContractMethod<
      [_token: AddressLike, _serial: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeDelegateNFTs'): TypedContractMethod<
      [_tokens: AddressLike[], _serials: BigNumberish[][], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeDelegateWallet'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'TokenDelegated'): TypedContractEvent<TokenDelegatedEvent.InputTuple, TokenDelegatedEvent.OutputTuple, TokenDelegatedEvent.OutputObject>;
getEvent(key: 'WalletDelegated'): TypedContractEvent<WalletDelegatedEvent.InputTuple, WalletDelegatedEvent.OutputTuple, WalletDelegatedEvent.OutputObject>;

    filters: {
      
      'TokenDelegated(address,uint256,address,address,bool)': TypedContractEvent<TokenDelegatedEvent.InputTuple, TokenDelegatedEvent.OutputTuple, TokenDelegatedEvent.OutputObject>;
      TokenDelegated: TypedContractEvent<TokenDelegatedEvent.InputTuple, TokenDelegatedEvent.OutputTuple, TokenDelegatedEvent.OutputObject>;
    

      'WalletDelegated(address,address,bool)': TypedContractEvent<WalletDelegatedEvent.InputTuple, WalletDelegatedEvent.OutputTuple, WalletDelegatedEvent.OutputObject>;
      WalletDelegated: TypedContractEvent<WalletDelegatedEvent.InputTuple, WalletDelegatedEvent.OutputTuple, WalletDelegatedEvent.OutputObject>;
    
    };
  }