/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace UnifiedTokenSwap {
      
    export type SwapConfigStruct = {outputToken: AddressLike, treasury: AddressLike, useGraveyard: boolean, outputSerial: BigNumberish}

    export type SwapConfigStructOutput = [outputToken: string, treasury: string, useGraveyard: boolean, outputSerial: bigint] & {outputToken: string, treasury: string, useGraveyard: boolean, outputSerial: bigint }
  
    }

  export interface UnifiedTokenSwapInterface extends Interface {
    getFunction(nameOrSignature: "addAdmin" | "addOutputToken" | "addSwapConfigs" | "getAdmins" | "getInputTokens" | "getOutputTokens" | "getSwapConfigs" | "graveyard" | "isAdmin" | "isTokenAssociated" | "paused" | "removeAdmin" | "removeSwapConfigs" | "stakeNFTs" | "swapConfigs" | "swapNFTs" | "transferHbar" | "unstakeNFTs" | "updateGraveyard" | "updatePauseStatus"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AdminChanged" | "SwapEvent"): EventFragment;

    encodeFunctionData(functionFragment: 'addAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'addOutputToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'addSwapConfigs', values: [AddressLike[], BigNumberish[], UnifiedTokenSwap.SwapConfigStruct[]]): string;
encodeFunctionData(functionFragment: 'getAdmins', values?: undefined): string;
encodeFunctionData(functionFragment: 'getInputTokens', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOutputTokens', values?: undefined): string;
encodeFunctionData(functionFragment: 'getSwapConfigs', values: [AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'graveyard', values?: undefined): string;
encodeFunctionData(functionFragment: 'isAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isTokenAssociated', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'removeSwapConfigs', values: [AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'stakeNFTs', values: [AddressLike, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'swapConfigs', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'swapNFTs', values: [AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'transferHbar', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'unstakeNFTs', values: [AddressLike, BigNumberish[], AddressLike]): string;
encodeFunctionData(functionFragment: 'updateGraveyard', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updatePauseStatus', values: [boolean]): string;

    decodeFunctionResult(functionFragment: 'addAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addOutputToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addSwapConfigs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAdmins', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getInputTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOutputTokens', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getSwapConfigs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'graveyard', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isTokenAssociated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeSwapConfigs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakeNFTs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapConfigs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapNFTs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferHbar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unstakeNFTs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateGraveyard', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePauseStatus', data: BytesLike): Result;
  }

  
    export namespace AdminChangedEvent {
      export type InputTuple = [admin: AddressLike, added: boolean];
      export type OutputTuple = [admin: string, added: boolean];
      export interface OutputObject {admin: string, added: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SwapEventEvent {
      export type InputTuple = [user: AddressLike, inputToken: AddressLike, inputSerial: BigNumberish, outputToken: AddressLike, outputSerial: BigNumberish, message: string];
      export type OutputTuple = [user: string, inputToken: string, inputSerial: bigint, outputToken: string, outputSerial: bigint, message: string];
      export interface OutputObject {user: string, inputToken: string, inputSerial: bigint, outputToken: string, outputSerial: bigint, message: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface UnifiedTokenSwap extends BaseContract {
    
    connect(runner?: ContractRunner | null): UnifiedTokenSwap;
    waitForDeployment(): Promise<this>;

    interface: UnifiedTokenSwapInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addAdmin: TypedContractMethod<
      [_admin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    addOutputToken: TypedContractMethod<
      [_token: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    addSwapConfigs: TypedContractMethod<
      [_inputTokens: AddressLike[], _inputSerials: BigNumberish[], _configs: UnifiedTokenSwap.SwapConfigStruct[], ],
      [void],
      'nonpayable'
    >
    

    
    getAdmins: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getInputTokens: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getOutputTokens: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getSwapConfigs: TypedContractMethod<
      [_inputTokens: AddressLike[], _inputSerials: BigNumberish[], ],
      [UnifiedTokenSwap.SwapConfigStructOutput[]],
      'view'
    >
    

    
    graveyard: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isAdmin: TypedContractMethod<
      [_account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isTokenAssociated: TypedContractMethod<
      [_token: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    removeAdmin: TypedContractMethod<
      [_admin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    removeSwapConfigs: TypedContractMethod<
      [_inputTokens: AddressLike[], _inputSerials: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    stakeNFTs: TypedContractMethod<
      [token: AddressLike, serials: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    swapConfigs: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, boolean, bigint] & {outputToken: string, treasury: string, useGraveyard: boolean, outputSerial: bigint }],
      'view'
    >
    

    
    swapNFTs: TypedContractMethod<
      [_inputTokens: AddressLike[], _inputSerials: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    transferHbar: TypedContractMethod<
      [receiverAddress: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    unstakeNFTs: TypedContractMethod<
      [token: AddressLike, serials: BigNumberish[], receiver: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateGraveyard: TypedContractMethod<
      [_graveyard: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updatePauseStatus: TypedContractMethod<
      [_paused: boolean, ],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addAdmin'): TypedContractMethod<
      [_admin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addOutputToken'): TypedContractMethod<
      [_token: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addSwapConfigs'): TypedContractMethod<
      [_inputTokens: AddressLike[], _inputSerials: BigNumberish[], _configs: UnifiedTokenSwap.SwapConfigStruct[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAdmins'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getInputTokens'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getOutputTokens'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getSwapConfigs'): TypedContractMethod<
      [_inputTokens: AddressLike[], _inputSerials: BigNumberish[], ],
      [UnifiedTokenSwap.SwapConfigStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'graveyard'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isAdmin'): TypedContractMethod<
      [_account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isTokenAssociated'): TypedContractMethod<
      [_token: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'removeAdmin'): TypedContractMethod<
      [_admin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeSwapConfigs'): TypedContractMethod<
      [_inputTokens: AddressLike[], _inputSerials: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakeNFTs'): TypedContractMethod<
      [token: AddressLike, serials: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapConfigs'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, boolean, bigint] & {outputToken: string, treasury: string, useGraveyard: boolean, outputSerial: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'swapNFTs'): TypedContractMethod<
      [_inputTokens: AddressLike[], _inputSerials: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferHbar'): TypedContractMethod<
      [receiverAddress: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unstakeNFTs'): TypedContractMethod<
      [token: AddressLike, serials: BigNumberish[], receiver: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateGraveyard'): TypedContractMethod<
      [_graveyard: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePauseStatus'): TypedContractMethod<
      [_paused: boolean, ],
      [boolean],
      'nonpayable'
    >;

    getEvent(key: 'AdminChanged'): TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
getEvent(key: 'SwapEvent'): TypedContractEvent<SwapEventEvent.InputTuple, SwapEventEvent.OutputTuple, SwapEventEvent.OutputObject>;

    filters: {
      
      'AdminChanged(address,bool)': TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
      AdminChanged: TypedContractEvent<AdminChangedEvent.InputTuple, AdminChangedEvent.OutputTuple, AdminChangedEvent.OutputObject>;
    

      'SwapEvent(address,address,uint256,address,uint256,string)': TypedContractEvent<SwapEventEvent.InputTuple, SwapEventEvent.OutputTuple, SwapEventEvent.OutputObject>;
      SwapEvent: TypedContractEvent<SwapEventEvent.InputTuple, SwapEventEvent.OutputTuple, SwapEventEvent.OutputObject>;
    
    };
  }