/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IHederaTokenService {
      
    export type ExpiryStruct = {second: BigNumberish, autoRenewAccount: AddressLike, autoRenewPeriod: BigNumberish}

    export type ExpiryStructOutput = [second: bigint, autoRenewAccount: string, autoRenewPeriod: bigint] & {second: bigint, autoRenewAccount: string, autoRenewPeriod: bigint }
  

    export type KeyValueStruct = {inheritAccountKey: boolean, contractId: AddressLike, ed25519: BytesLike, ECDSA_secp256k1: BytesLike, delegatableContractId: AddressLike}

    export type KeyValueStructOutput = [inheritAccountKey: boolean, contractId: string, ed25519: string, ECDSA_secp256k1: string, delegatableContractId: string] & {inheritAccountKey: boolean, contractId: string, ed25519: string, ECDSA_secp256k1: string, delegatableContractId: string }
  

    export type TokenKeyStruct = {keyType: BigNumberish, key: IHederaTokenService.KeyValueStruct}

    export type TokenKeyStructOutput = [keyType: bigint, key: IHederaTokenService.KeyValueStructOutput] & {keyType: bigint, key: IHederaTokenService.KeyValueStructOutput }
  
    }

  export interface BaseTokenSwapInterface extends Interface {
    getFunction(nameOrSignature: "getSerials" | "getTokenExpiryInfo" | "getTokenKey" | "grantTokenKyc" | "isKyc" | "lazyGasStation" | "lazyPmtAmt" | "lazyToken" | "owner" | "pauseToken" | "paused" | "removeSwapConfig" | "renounceOwnership" | "retrieveLazy" | "revokeTokenKyc" | "swapToken" | "swapTokenTreasury" | "transferHbar" | "transferOwnership" | "unpauseToken" | "updateClaimAmount" | "updateLGS" | "updateLazyToken" | "updatePauseStatus" | "updateSwapConfig" | "updateSwapToken" | "updateSwapTokenTreasury" | "updateTokenExpiryInfo" | "updateTokenKeys"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "TokenSwapEvent"): EventFragment;

    encodeFunctionData(functionFragment: 'getSerials', values: [BytesLike[]]): string;
encodeFunctionData(functionFragment: 'getTokenExpiryInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTokenKey', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'grantTokenKyc', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isKyc', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'lazyGasStation', values?: undefined): string;
encodeFunctionData(functionFragment: 'lazyPmtAmt', values?: undefined): string;
encodeFunctionData(functionFragment: 'lazyToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pauseToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'removeSwapConfig', values: [BytesLike[]]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'retrieveLazy', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeTokenKyc', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'swapToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'swapTokenTreasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferHbar', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpauseToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateClaimAmount', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'updateLGS', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateLazyToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updatePauseStatus', values: [boolean]): string;
encodeFunctionData(functionFragment: 'updateSwapConfig', values: [BigNumberish[], BytesLike[]]): string;
encodeFunctionData(functionFragment: 'updateSwapToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateSwapTokenTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateTokenExpiryInfo', values: [AddressLike, IHederaTokenService.ExpiryStruct]): string;
encodeFunctionData(functionFragment: 'updateTokenKeys', values: [AddressLike, IHederaTokenService.TokenKeyStruct[]]): string;

    decodeFunctionResult(functionFragment: 'getSerials', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenExpiryInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantTokenKyc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isKyc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lazyGasStation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lazyPmtAmt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lazyToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeSwapConfig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'retrieveLazy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeTokenKyc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swapTokenTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferHbar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpauseToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateClaimAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateLGS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateLazyToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updatePauseStatus', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateSwapConfig', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateSwapToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateSwapTokenTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTokenExpiryInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTokenKeys', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenSwapEventEvent {
      export type InputTuple = [user: AddressLike, oldToken: AddressLike, oldSerial: BigNumberish, newToken: AddressLike, newSerial: BigNumberish, message: string];
      export type OutputTuple = [user: string, oldToken: string, oldSerial: bigint, newToken: string, newSerial: bigint, message: string];
      export interface OutputObject {user: string, oldToken: string, oldSerial: bigint, newToken: string, newSerial: bigint, message: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface BaseTokenSwap extends BaseContract {
    
    connect(runner?: ContractRunner | null): BaseTokenSwap;
    waitForDeployment(): Promise<this>;

    interface: BaseTokenSwapInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getSerials: TypedContractMethod<
      [swapHashes: BytesLike[], ],
      [bigint[]],
      'view'
    >
    

    
    getTokenExpiryInfo: TypedContractMethod<
      [token: AddressLike, ],
      [[bigint, IHederaTokenService.ExpiryStructOutput] & {responseCode: bigint, expiryInfo: IHederaTokenService.ExpiryStructOutput }],
      'nonpayable'
    >
    

    
    getTokenKey: TypedContractMethod<
      [token: AddressLike, keyType: BigNumberish, ],
      [[bigint, IHederaTokenService.KeyValueStructOutput] & {responseCode: bigint, key: IHederaTokenService.KeyValueStructOutput }],
      'nonpayable'
    >
    

    
    grantTokenKyc: TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    isKyc: TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [[bigint, boolean] & {responseCode: bigint, kycGranted: boolean }],
      'nonpayable'
    >
    

    
    lazyGasStation: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    lazyPmtAmt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    lazyToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pauseToken: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    removeSwapConfig: TypedContractMethod<
      [_swapHashes: BytesLike[], ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    retrieveLazy: TypedContractMethod<
      [_receiver: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revokeTokenKyc: TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    swapToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    swapTokenTreasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferHbar: TypedContractMethod<
      [receiverAddress: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpauseToken: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    updateClaimAmount: TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    updateLGS: TypedContractMethod<
      [_lgs: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateLazyToken: TypedContractMethod<
      [_lazy: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updatePauseStatus: TypedContractMethod<
      [_paused: boolean, ],
      [boolean],
      'nonpayable'
    >
    

    
    updateSwapConfig: TypedContractMethod<
      [newSerials: BigNumberish[], swapHashes: BytesLike[], ],
      [void],
      'nonpayable'
    >
    

    
    updateSwapToken: TypedContractMethod<
      [_swapToken: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateSwapTokenTreasury: TypedContractMethod<
      [_newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateTokenExpiryInfo: TypedContractMethod<
      [token: AddressLike, expiryInfo: IHederaTokenService.ExpiryStruct, ],
      [bigint],
      'nonpayable'
    >
    

    
    updateTokenKeys: TypedContractMethod<
      [token: AddressLike, keys: IHederaTokenService.TokenKeyStruct[], ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getSerials'): TypedContractMethod<
      [swapHashes: BytesLike[], ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenExpiryInfo'): TypedContractMethod<
      [token: AddressLike, ],
      [[bigint, IHederaTokenService.ExpiryStructOutput] & {responseCode: bigint, expiryInfo: IHederaTokenService.ExpiryStructOutput }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getTokenKey'): TypedContractMethod<
      [token: AddressLike, keyType: BigNumberish, ],
      [[bigint, IHederaTokenService.KeyValueStructOutput] & {responseCode: bigint, key: IHederaTokenService.KeyValueStructOutput }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantTokenKyc'): TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isKyc'): TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [[bigint, boolean] & {responseCode: bigint, kycGranted: boolean }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'lazyGasStation'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'lazyPmtAmt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lazyToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pauseToken'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'removeSwapConfig'): TypedContractMethod<
      [_swapHashes: BytesLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'retrieveLazy'): TypedContractMethod<
      [_receiver: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeTokenKyc'): TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swapToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'swapTokenTreasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferHbar'): TypedContractMethod<
      [receiverAddress: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpauseToken'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateClaimAmount'): TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateLGS'): TypedContractMethod<
      [_lgs: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateLazyToken'): TypedContractMethod<
      [_lazy: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updatePauseStatus'): TypedContractMethod<
      [_paused: boolean, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateSwapConfig'): TypedContractMethod<
      [newSerials: BigNumberish[], swapHashes: BytesLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateSwapToken'): TypedContractMethod<
      [_swapToken: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateSwapTokenTreasury'): TypedContractMethod<
      [_newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTokenExpiryInfo'): TypedContractMethod<
      [token: AddressLike, expiryInfo: IHederaTokenService.ExpiryStruct, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTokenKeys'): TypedContractMethod<
      [token: AddressLike, keys: IHederaTokenService.TokenKeyStruct[], ],
      [bigint],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TokenSwapEvent'): TypedContractEvent<TokenSwapEventEvent.InputTuple, TokenSwapEventEvent.OutputTuple, TokenSwapEventEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TokenSwapEvent(address,address,uint256,address,uint256,string)': TypedContractEvent<TokenSwapEventEvent.InputTuple, TokenSwapEventEvent.OutputTuple, TokenSwapEventEvent.OutputObject>;
      TokenSwapEvent: TypedContractEvent<TokenSwapEventEvent.InputTuple, TokenSwapEventEvent.OutputTuple, TokenSwapEventEvent.OutputObject>;
    
    };
  }