/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../../common.js"
  

  export interface ILazyGasStationInterface extends Interface {
    getFunction(nameOrSignature: "addAdmin" | "addAuthorizer" | "addContractUser" | "drawLazyFrom" | "drawLazyFromPayTo" | "lazySCT" | "payoutLazy" | "refillLazy" | "removeAdmin" | "removeAuthorizer" | "removeContractUser"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'addAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'addAuthorizer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'addContractUser', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'drawLazyFrom', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'drawLazyFromPayTo', values: [AddressLike, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'lazySCT', values?: undefined): string;
encodeFunctionData(functionFragment: 'payoutLazy', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'refillLazy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'removeAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'removeAuthorizer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'removeContractUser', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'addAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addAuthorizer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addContractUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'drawLazyFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'drawLazyFromPayTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lazySCT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payoutLazy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refillLazy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeAuthorizer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeContractUser', data: BytesLike): Result;
  }

  

  export interface ILazyGasStation extends BaseContract {
    
    connect(runner?: ContractRunner | null): ILazyGasStation;
    waitForDeployment(): Promise<this>;

    interface: ILazyGasStationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addAdmin: TypedContractMethod<
      [_admin: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    addAuthorizer: TypedContractMethod<
      [_authorized: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    addContractUser: TypedContractMethod<
      [_deployer: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    drawLazyFrom: TypedContractMethod<
      [_user: AddressLike, _amount: BigNumberish, _burnPercentage: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    drawLazyFromPayTo: TypedContractMethod<
      [_user: AddressLike, _amount: BigNumberish, _burnPercentage: BigNumberish, _payTo: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    lazySCT: TypedContractMethod<
      [],
      [string],
      'nonpayable'
    >
    

    
    payoutLazy: TypedContractMethod<
      [_user: AddressLike, _amount: BigNumberish, _burnPercentage: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    refillLazy: TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    removeAdmin: TypedContractMethod<
      [_admin: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    removeAuthorizer: TypedContractMethod<
      [_authorized: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    removeContractUser: TypedContractMethod<
      [_deployer: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addAdmin'): TypedContractMethod<
      [_admin: AddressLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addAuthorizer'): TypedContractMethod<
      [_authorized: AddressLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addContractUser'): TypedContractMethod<
      [_deployer: AddressLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'drawLazyFrom'): TypedContractMethod<
      [_user: AddressLike, _amount: BigNumberish, _burnPercentage: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'drawLazyFromPayTo'): TypedContractMethod<
      [_user: AddressLike, _amount: BigNumberish, _burnPercentage: BigNumberish, _payTo: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'lazySCT'): TypedContractMethod<
      [],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'payoutLazy'): TypedContractMethod<
      [_user: AddressLike, _amount: BigNumberish, _burnPercentage: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'refillLazy'): TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeAdmin'): TypedContractMethod<
      [_admin: AddressLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeAuthorizer'): TypedContractMethod<
      [_authorized: AddressLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeContractUser'): TypedContractMethod<
      [_deployer: AddressLike, ],
      [boolean],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }