/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iBurnableHtsSol from './IBurnableHTS.sol/index.js';
export type { iBurnableHtsSol };
import type * as iHederaTokenServiceSol from './IHederaTokenService.sol/index.js';
export type { iHederaTokenServiceSol };
import type * as iHederaTokenServiceLiteSol from './IHederaTokenServiceLite.sol/index.js';
export type { iHederaTokenServiceLiteSol };
import type * as iLazyGasStationSol from './ILazyGasStation.sol/index.js';
export type { iLazyGasStationSol };
import type * as iRolesSol from './IRoles.sol/index.js';
export type { iRolesSol };