/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace IHederaTokenService {
      
    export type ExpiryStruct = {second: BigNumberish, autoRenewAccount: AddressLike, autoRenewPeriod: BigNumberish}

    export type ExpiryStructOutput = [second: bigint, autoRenewAccount: string, autoRenewPeriod: bigint] & {second: bigint, autoRenewAccount: string, autoRenewPeriod: bigint }
  

    export type KeyValueStruct = {inheritAccountKey: boolean, contractId: AddressLike, ed25519: BytesLike, ECDSA_secp256k1: BytesLike, delegatableContractId: AddressLike}

    export type KeyValueStructOutput = [inheritAccountKey: boolean, contractId: string, ed25519: string, ECDSA_secp256k1: string, delegatableContractId: string] & {inheritAccountKey: boolean, contractId: string, ed25519: string, ECDSA_secp256k1: string, delegatableContractId: string }
  

    export type TokenKeyStruct = {keyType: BigNumberish, key: IHederaTokenService.KeyValueStruct}

    export type TokenKeyStructOutput = [keyType: bigint, key: IHederaTokenService.KeyValueStructOutput] & {keyType: bigint, key: IHederaTokenService.KeyValueStructOutput }
  
    }

  export interface LAZYTokenCreatorInterface extends Interface {
    getFunction(nameOrSignature: "addAllowanceWhitelist" | "approveAllowance" | "burn" | "checkAllowance" | "createFungibleWithBurn" | "getAllowanceWhitelist" | "getTokenExpiryInfo" | "getTokenKey" | "grantTokenKyc" | "isAddressWL" | "isKyc" | "owner" | "pauseToken" | "removeAllowanceWhitelist" | "renounceOwnership" | "revokeTokenKyc" | "transferHTS" | "transferHbar" | "transferOwnership" | "unpauseToken" | "updateTokenExpiryInfo" | "updateTokenKeys"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "TokenControllerMessage"): EventFragment;

    encodeFunctionData(functionFragment: 'addAllowanceWhitelist', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'approveAllowance', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'burn', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'checkAllowance', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'createFungibleWithBurn', values: [string, string, string, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAllowanceWhitelist', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTokenExpiryInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTokenKey', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'grantTokenKyc', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isAddressWL', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isKyc', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pauseToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'removeAllowanceWhitelist', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'revokeTokenKyc', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'transferHTS', values: [AddressLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferHbar', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpauseToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateTokenExpiryInfo', values: [AddressLike, IHederaTokenService.ExpiryStruct]): string;
encodeFunctionData(functionFragment: 'updateTokenKeys', values: [AddressLike, IHederaTokenService.TokenKeyStruct[]]): string;

    decodeFunctionResult(functionFragment: 'addAllowanceWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveAllowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'burn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'checkAllowance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createFungibleWithBurn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAllowanceWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenExpiryInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantTokenKyc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAddressWL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isKyc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeAllowanceWhitelist', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeTokenKyc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferHTS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferHbar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpauseToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTokenExpiryInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTokenKeys', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenControllerMessageEvent {
      export type InputTuple = [msgType: string, fromAddress: AddressLike, amount: BigNumberish, message: string];
      export type OutputTuple = [msgType: string, fromAddress: string, amount: bigint, message: string];
      export interface OutputObject {msgType: string, fromAddress: string, amount: bigint, message: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LAZYTokenCreator extends BaseContract {
    
    connect(runner?: ContractRunner | null): LAZYTokenCreator;
    waitForDeployment(): Promise<this>;

    interface: LAZYTokenCreatorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addAllowanceWhitelist: TypedContractMethod<
      [newAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    approveAllowance: TypedContractMethod<
      [token: AddressLike, spender: AddressLike, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    burn: TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    checkAllowance: TypedContractMethod<
      [token: AddressLike, spender: AddressLike, ],
      [[bigint, bigint] & {responseCode: bigint, amount: bigint }],
      'nonpayable'
    >
    

    
    createFungibleWithBurn: TypedContractMethod<
      [name: string, symbol: string, memo: string, initialSupply: BigNumberish, decimals: BigNumberish, maxSupply: BigNumberish, ],
      [string],
      'payable'
    >
    

    
    getAllowanceWhitelist: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getTokenExpiryInfo: TypedContractMethod<
      [token: AddressLike, ],
      [[bigint, IHederaTokenService.ExpiryStructOutput] & {responseCode: bigint, expiryInfo: IHederaTokenService.ExpiryStructOutput }],
      'nonpayable'
    >
    

    
    getTokenKey: TypedContractMethod<
      [token: AddressLike, keyType: BigNumberish, ],
      [[bigint, IHederaTokenService.KeyValueStructOutput] & {responseCode: bigint, key: IHederaTokenService.KeyValueStructOutput }],
      'nonpayable'
    >
    

    
    grantTokenKyc: TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    isAddressWL: TypedContractMethod<
      [addressToCheck: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isKyc: TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [[bigint, boolean] & {responseCode: bigint, kycGranted: boolean }],
      'nonpayable'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pauseToken: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    removeAllowanceWhitelist: TypedContractMethod<
      [oldAddress: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    revokeTokenKyc: TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    transferHTS: TypedContractMethod<
      [token: AddressLike, receiver: AddressLike, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    transferHbar: TypedContractMethod<
      [receiverAddress: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpauseToken: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    updateTokenExpiryInfo: TypedContractMethod<
      [token: AddressLike, expiryInfo: IHederaTokenService.ExpiryStruct, ],
      [bigint],
      'nonpayable'
    >
    

    
    updateTokenKeys: TypedContractMethod<
      [token: AddressLike, keys: IHederaTokenService.TokenKeyStruct[], ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addAllowanceWhitelist'): TypedContractMethod<
      [newAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'approveAllowance'): TypedContractMethod<
      [token: AddressLike, spender: AddressLike, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'burn'): TypedContractMethod<
      [token: AddressLike, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'checkAllowance'): TypedContractMethod<
      [token: AddressLike, spender: AddressLike, ],
      [[bigint, bigint] & {responseCode: bigint, amount: bigint }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createFungibleWithBurn'): TypedContractMethod<
      [name: string, symbol: string, memo: string, initialSupply: BigNumberish, decimals: BigNumberish, maxSupply: BigNumberish, ],
      [string],
      'payable'
    >;
getFunction(nameOrSignature: 'getAllowanceWhitelist'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenExpiryInfo'): TypedContractMethod<
      [token: AddressLike, ],
      [[bigint, IHederaTokenService.ExpiryStructOutput] & {responseCode: bigint, expiryInfo: IHederaTokenService.ExpiryStructOutput }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getTokenKey'): TypedContractMethod<
      [token: AddressLike, keyType: BigNumberish, ],
      [[bigint, IHederaTokenService.KeyValueStructOutput] & {responseCode: bigint, key: IHederaTokenService.KeyValueStructOutput }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantTokenKyc'): TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isAddressWL'): TypedContractMethod<
      [addressToCheck: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isKyc'): TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [[bigint, boolean] & {responseCode: bigint, kycGranted: boolean }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pauseToken'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeAllowanceWhitelist'): TypedContractMethod<
      [oldAddress: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeTokenKyc'): TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferHTS'): TypedContractMethod<
      [token: AddressLike, receiver: AddressLike, amount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferHbar'): TypedContractMethod<
      [receiverAddress: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpauseToken'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTokenExpiryInfo'): TypedContractMethod<
      [token: AddressLike, expiryInfo: IHederaTokenService.ExpiryStruct, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTokenKeys'): TypedContractMethod<
      [token: AddressLike, keys: IHederaTokenService.TokenKeyStruct[], ],
      [bigint],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'TokenControllerMessage'): TypedContractEvent<TokenControllerMessageEvent.InputTuple, TokenControllerMessageEvent.OutputTuple, TokenControllerMessageEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'TokenControllerMessage(string,address,uint256,string)': TypedContractEvent<TokenControllerMessageEvent.InputTuple, TokenControllerMessageEvent.OutputTuple, TokenControllerMessageEvent.OutputObject>;
      TokenControllerMessage: TypedContractEvent<TokenControllerMessageEvent.InputTuple, TokenControllerMessageEvent.OutputTuple, TokenControllerMessageEvent.OutputObject>;
    
    };
  }