/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IHederaTokenService {
      
    export type ExpiryStruct = {second: BigNumberish, autoRenewAccount: AddressLike, autoRenewPeriod: BigNumberish}

    export type ExpiryStructOutput = [second: bigint, autoRenewAccount: string, autoRenewPeriod: bigint] & {second: bigint, autoRenewAccount: string, autoRenewPeriod: bigint }
  

    export type KeyValueStruct = {inheritAccountKey: boolean, contractId: AddressLike, ed25519: BytesLike, ECDSA_secp256k1: BytesLike, delegatableContractId: AddressLike}

    export type KeyValueStructOutput = [inheritAccountKey: boolean, contractId: string, ed25519: string, ECDSA_secp256k1: string, delegatableContractId: string] & {inheritAccountKey: boolean, contractId: string, ed25519: string, ECDSA_secp256k1: string, delegatableContractId: string }
  

    export type TokenKeyStruct = {keyType: BigNumberish, key: IHederaTokenService.KeyValueStruct}

    export type TokenKeyStructOutput = [keyType: bigint, key: IHederaTokenService.KeyValueStructOutput] & {keyType: bigint, key: IHederaTokenService.KeyValueStructOutput }
  
    }

  export interface LazyGasStationInterface extends Interface {
    getFunction(nameOrSignature: "addAdmin" | "addAuthorizer" | "addContractUser" | "drawLazyFrom" | "drawLazyFromPayTo" | "getAdmins" | "getAuthorizers" | "getContractUsers" | "getTokenExpiryInfo" | "getTokenKey" | "grantTokenKyc" | "isAdmin" | "isAuthorizer" | "isContractUser" | "isKyc" | "lazySCT" | "lazyToken" | "pauseToken" | "payoutLazy" | "refillHbar" | "refillLazy" | "removeAdmin" | "removeAuthorizer" | "removeContractUser" | "retrieveLazy" | "revokeTokenKyc" | "transferHbar" | "unpauseToken" | "updateTokenExpiryInfo" | "updateTokenKeys"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "GasStationAccessControlEvent" | "GasStationFunding" | "GasStationRefillEvent"): EventFragment;

    encodeFunctionData(functionFragment: 'addAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'addAuthorizer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'addContractUser', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'drawLazyFrom', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'drawLazyFromPayTo', values: [AddressLike, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'getAdmins', values?: undefined): string;
encodeFunctionData(functionFragment: 'getAuthorizers', values?: undefined): string;
encodeFunctionData(functionFragment: 'getContractUsers', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTokenExpiryInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getTokenKey', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'grantTokenKyc', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isAuthorizer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isContractUser', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isKyc', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'lazySCT', values?: undefined): string;
encodeFunctionData(functionFragment: 'lazyToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'pauseToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'payoutLazy', values: [AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'refillHbar', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'refillLazy', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'removeAdmin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'removeAuthorizer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'removeContractUser', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'retrieveLazy', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'revokeTokenKyc', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'transferHbar', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'unpauseToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateTokenExpiryInfo', values: [AddressLike, IHederaTokenService.ExpiryStruct]): string;
encodeFunctionData(functionFragment: 'updateTokenKeys', values: [AddressLike, IHederaTokenService.TokenKeyStruct[]]): string;

    decodeFunctionResult(functionFragment: 'addAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addAuthorizer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addContractUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'drawLazyFrom', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'drawLazyFromPayTo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAdmins', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAuthorizers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getContractUsers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenExpiryInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenKey', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantTokenKyc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAuthorizer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isContractUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isKyc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lazySCT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lazyToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pauseToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'payoutLazy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refillHbar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refillLazy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeAuthorizer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'removeContractUser', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'retrieveLazy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeTokenKyc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferHbar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpauseToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTokenExpiryInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateTokenKeys', data: BytesLike): Result;
  }

  
    export namespace GasStationAccessControlEventEvent {
      export type InputTuple = [_executor: AddressLike, _address: AddressLike, _added: boolean, _role: BigNumberish];
      export type OutputTuple = [_executor: string, _address: string, _added: boolean, _role: bigint];
      export interface OutputObject {_executor: string, _address: string, _added: boolean, _role: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GasStationFundingEvent {
      export type InputTuple = [_callingContract: AddressLike, _user: AddressLike, _amount: BigNumberish, _burnPercentage: BigNumberish, _fromUser: boolean];
      export type OutputTuple = [_callingContract: string, _user: string, _amount: bigint, _burnPercentage: bigint, _fromUser: boolean];
      export interface OutputObject {_callingContract: string, _user: string, _amount: bigint, _burnPercentage: bigint, _fromUser: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace GasStationRefillEventEvent {
      export type InputTuple = [_callingContract: AddressLike, _amount: BigNumberish, _type: BigNumberish];
      export type OutputTuple = [_callingContract: string, _amount: bigint, _type: bigint];
      export interface OutputObject {_callingContract: string, _amount: bigint, _type: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface LazyGasStation extends BaseContract {
    
    connect(runner?: ContractRunner | null): LazyGasStation;
    waitForDeployment(): Promise<this>;

    interface: LazyGasStationInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addAdmin: TypedContractMethod<
      [_admin: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    addAuthorizer: TypedContractMethod<
      [_authorized: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    addContractUser: TypedContractMethod<
      [_deployer: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    drawLazyFrom: TypedContractMethod<
      [_user: AddressLike, _amount: BigNumberish, _burnPercentage: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    drawLazyFromPayTo: TypedContractMethod<
      [_user: AddressLike, _amount: BigNumberish, _burnPercentage: BigNumberish, _payTo: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    getAdmins: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getAuthorizers: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getContractUsers: TypedContractMethod<
      [],
      [string[]],
      'view'
    >
    

    
    getTokenExpiryInfo: TypedContractMethod<
      [token: AddressLike, ],
      [[bigint, IHederaTokenService.ExpiryStructOutput] & {responseCode: bigint, expiryInfo: IHederaTokenService.ExpiryStructOutput }],
      'nonpayable'
    >
    

    
    getTokenKey: TypedContractMethod<
      [token: AddressLike, keyType: BigNumberish, ],
      [[bigint, IHederaTokenService.KeyValueStructOutput] & {responseCode: bigint, key: IHederaTokenService.KeyValueStructOutput }],
      'nonpayable'
    >
    

    
    grantTokenKyc: TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    isAdmin: TypedContractMethod<
      [_admin: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isAuthorizer: TypedContractMethod<
      [_authorizer: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isContractUser: TypedContractMethod<
      [_contractUser: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isKyc: TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [[bigint, boolean] & {responseCode: bigint, kycGranted: boolean }],
      'nonpayable'
    >
    

    
    lazySCT: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    lazyToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pauseToken: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    payoutLazy: TypedContractMethod<
      [_user: AddressLike, _amount: BigNumberish, _burnPercentage: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    refillHbar: TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    refillLazy: TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    removeAdmin: TypedContractMethod<
      [_admin: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    removeAuthorizer: TypedContractMethod<
      [_authorized: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    removeContractUser: TypedContractMethod<
      [_deployer: AddressLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    retrieveLazy: TypedContractMethod<
      [_receiver: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    revokeTokenKyc: TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    transferHbar: TypedContractMethod<
      [receiverAddress: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    unpauseToken: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'nonpayable'
    >
    

    
    updateTokenExpiryInfo: TypedContractMethod<
      [token: AddressLike, expiryInfo: IHederaTokenService.ExpiryStruct, ],
      [bigint],
      'nonpayable'
    >
    

    
    updateTokenKeys: TypedContractMethod<
      [token: AddressLike, keys: IHederaTokenService.TokenKeyStruct[], ],
      [bigint],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addAdmin'): TypedContractMethod<
      [_admin: AddressLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addAuthorizer'): TypedContractMethod<
      [_authorized: AddressLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addContractUser'): TypedContractMethod<
      [_deployer: AddressLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'drawLazyFrom'): TypedContractMethod<
      [_user: AddressLike, _amount: BigNumberish, _burnPercentage: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'drawLazyFromPayTo'): TypedContractMethod<
      [_user: AddressLike, _amount: BigNumberish, _burnPercentage: BigNumberish, _payTo: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAdmins'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getAuthorizers'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getContractUsers'): TypedContractMethod<
      [],
      [string[]],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenExpiryInfo'): TypedContractMethod<
      [token: AddressLike, ],
      [[bigint, IHederaTokenService.ExpiryStructOutput] & {responseCode: bigint, expiryInfo: IHederaTokenService.ExpiryStructOutput }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getTokenKey'): TypedContractMethod<
      [token: AddressLike, keyType: BigNumberish, ],
      [[bigint, IHederaTokenService.KeyValueStructOutput] & {responseCode: bigint, key: IHederaTokenService.KeyValueStructOutput }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'grantTokenKyc'): TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isAdmin'): TypedContractMethod<
      [_admin: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isAuthorizer'): TypedContractMethod<
      [_authorizer: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isContractUser'): TypedContractMethod<
      [_contractUser: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isKyc'): TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [[bigint, boolean] & {responseCode: bigint, kycGranted: boolean }],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'lazySCT'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'lazyToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pauseToken'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'payoutLazy'): TypedContractMethod<
      [_user: AddressLike, _amount: BigNumberish, _burnPercentage: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'refillHbar'): TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'refillLazy'): TypedContractMethod<
      [_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeAdmin'): TypedContractMethod<
      [_admin: AddressLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeAuthorizer'): TypedContractMethod<
      [_authorized: AddressLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'removeContractUser'): TypedContractMethod<
      [_deployer: AddressLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'retrieveLazy'): TypedContractMethod<
      [_receiver: AddressLike, _amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeTokenKyc'): TypedContractMethod<
      [token: AddressLike, account: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferHbar'): TypedContractMethod<
      [receiverAddress: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpauseToken'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTokenExpiryInfo'): TypedContractMethod<
      [token: AddressLike, expiryInfo: IHederaTokenService.ExpiryStruct, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateTokenKeys'): TypedContractMethod<
      [token: AddressLike, keys: IHederaTokenService.TokenKeyStruct[], ],
      [bigint],
      'nonpayable'
    >;

    getEvent(key: 'GasStationAccessControlEvent'): TypedContractEvent<GasStationAccessControlEventEvent.InputTuple, GasStationAccessControlEventEvent.OutputTuple, GasStationAccessControlEventEvent.OutputObject>;
getEvent(key: 'GasStationFunding'): TypedContractEvent<GasStationFundingEvent.InputTuple, GasStationFundingEvent.OutputTuple, GasStationFundingEvent.OutputObject>;
getEvent(key: 'GasStationRefillEvent'): TypedContractEvent<GasStationRefillEventEvent.InputTuple, GasStationRefillEventEvent.OutputTuple, GasStationRefillEventEvent.OutputObject>;

    filters: {
      
      'GasStationAccessControlEvent(address,address,bool,uint8)': TypedContractEvent<GasStationAccessControlEventEvent.InputTuple, GasStationAccessControlEventEvent.OutputTuple, GasStationAccessControlEventEvent.OutputObject>;
      GasStationAccessControlEvent: TypedContractEvent<GasStationAccessControlEventEvent.InputTuple, GasStationAccessControlEventEvent.OutputTuple, GasStationAccessControlEventEvent.OutputObject>;
    

      'GasStationFunding(address,address,uint256,uint256,bool)': TypedContractEvent<GasStationFundingEvent.InputTuple, GasStationFundingEvent.OutputTuple, GasStationFundingEvent.OutputObject>;
      GasStationFunding: TypedContractEvent<GasStationFundingEvent.InputTuple, GasStationFundingEvent.OutputTuple, GasStationFundingEvent.OutputObject>;
    

      'GasStationRefillEvent(address,uint256,uint8)': TypedContractEvent<GasStationRefillEventEvent.InputTuple, GasStationRefillEventEvent.OutputTuple, GasStationRefillEventEvent.OutputObject>;
      GasStationRefillEvent: TypedContractEvent<GasStationRefillEventEvent.InputTuple, GasStationRefillEventEvent.OutputTuple, GasStationRefillEventEvent.OutputObject>;
    
    };
  }