/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { ILazyGasStation, ILazyGasStationInterface } from "../../../interfaces/ILazyGasStation.sol/ILazyGasStation.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_admin",
        "type": "address"
      }
    ],
    "name": "addAdmin",
    "outputs": [
      {
        "internalType": "bool",
        "name": "_added",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_authorized",
        "type": "address"
      }
    ],
    "name": "addAuthorizer",
    "outputs": [
      {
        "internalType": "bool",
        "name": "_added",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_deployer",
        "type": "address"
      }
    ],
    "name": "addContractUser",
    "outputs": [
      {
        "internalType": "bool",
        "name": "_added",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_user",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "_amount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_burnPercentage",
        "type": "uint256"
      }
    ],
    "name": "drawLazyFrom",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_user",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "_amount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_burnPercentage",
        "type": "uint256"
      },
      {
        "internalType": "address",
        "name": "_payTo",
        "type": "address"
      }
    ],
    "name": "drawLazyFromPayTo",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "lazySCT",
    "outputs": [
      {
        "internalType": "address",
        "name": "_lazySCT",
        "type": "address"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_user",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "_amount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "_burnPercentage",
        "type": "uint256"
      }
    ],
    "name": "payoutLazy",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "_payoutAmount",
        "type": "uint256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint256",
        "name": "_amount",
        "type": "uint256"
      }
    ],
    "name": "refillLazy",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_admin",
        "type": "address"
      }
    ],
    "name": "removeAdmin",
    "outputs": [
      {
        "internalType": "bool",
        "name": "_removed",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_authorized",
        "type": "address"
      }
    ],
    "name": "removeAuthorizer",
    "outputs": [
      {
        "internalType": "bool",
        "name": "_removed",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "_deployer",
        "type": "address"
      }
    ],
    "name": "removeContractUser",
    "outputs": [
      {
        "internalType": "bool",
        "name": "_removed",
        "type": "bool"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class ILazyGasStation__factory {
    static readonly abi = _abi;
    static createInterface(): ILazyGasStationInterface {
      return new Interface(_abi) as ILazyGasStationInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): ILazyGasStation {
      return new Contract(address, _abi, runner) as unknown as ILazyGasStation;
    }
  }
  